# Generated by Django 3.2.9 on 2021-12-07 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('short_desc', models.CharField(blank=True, max_length=150, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('brand_name', models.CharField(max_length=150, verbose_name='Бренд')),
                ('size', models.CharField(max_length=2, verbose_name='Размер')),
                ('gender', models.CharField(max_length=1, verbose_name='Пол')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('short_desc', models.CharField(blank=True, max_length=150, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('brand_name', models.CharField(max_length=150, verbose_name='Бренд')),
                ('size', models.CharField(max_length=2, verbose_name='Размер')),
                ('gender', models.CharField(max_length=1, verbose_name='Пол')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
